# -*- coding: utf-8 -*-
"""planeacion_de_transporte

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BOOb5Cb3vT-SUtGswycDJhx2oStYL7Dx
"""

viajes_p= float(input("Introduce la cantidad de viajes por persona: "))
O_p_v= float(input("Introduce la ocupacion promedio del vehiculo: "))
viajes_v = viajes_p/O_p_v
print(f"el valor de los viajes por vehiculo es:{viajes_v:.2f}")